name: Сообщить о проблеме с картой
description: Для проблем, связанных с маппингом.
body:
- type: markdown
  attributes:
    value: |
      Спасибо, что нашли время заполнить issue. Этот шаблон предназначен для любых проблем, связанных с маппингом.
      Для обратной связи или помощи в запуске Space Station 14, пожалуйста, присоединяйтесь к нашему [Discord](https://discord.gg/ZU2wCTA7gt).
- type: input
  attributes:
    label: В какой версии возникла проблема?
    description: Вы можете найти версию, открыв список изменений в игре и посмотрев в правый нижний угол окна списка изменений.
    placeholder: wizards/aa1337b
  validations:
    required: false
- type: input
  attributes:
    label: На какой станции, шаттле или гриде возникла проблема?
    description: Название станции, шаттла или грида. Если вы не знаете название, попробуйте описать это.
    placeholder: Bagel
  validations:
    required: true
- type: textarea
  attributes:
    label: Описание
    description: |
      Четкое и краткое описание проблемы.
      Если проблема имеет визуальный характер, рассмотрите возможность публикации скриншота.
  validations:
    required: true
- type: textarea
  attributes:
    label: Воспроизведение
    description: Перечислите шаги, необходимые для воспроизведения проблемы.
    placeholder: |
      1.
      2.
      3.
      ...
  validations:
    required: true
- type: textarea
  attributes:
    label: Дополнительный контекст
    description: Добавьте здесь любой другой дополнительный контекст о проблеме.
  validations:
    required: false
